// Optimized constants for `pin_corner_to_sibling` and `pin_to_sibling_corner`.
{DEFINE PIN_TOPLEFT      } 0
{DEFINE PIN_TOPRIGHT     } 1
{DEFINE PIN_BOTTOMLEFT   } 2
{DEFINE PIN_BOTTOMRIGHT  } 3
{DEFINE PIN_CENTER_TOP   } 4
{DEFINE PIN_CENTER_RIGHT } 5
{DEFINE PIN_CENTER_BOTTOM} 6
{DEFINE PIN_CENTER_LEFT  } 7

// Constants for `roundedCorners`.
{DEFINE ROUND_CORNER_TOP_LEFT    } 1
{DEFINE ROUND_CORNER_TOP_RIGHT   } 2
{DEFINE ROUND_CORNER_BOTTOM_LEFT } 4
{DEFINE ROUND_CORNER_BOTTOM_RIGHT} 8
{DEFINE ROUND_CORNER_ALL} "$(ROUND_CORNER_TOP_LEFT | ROUND_CORNER_TOP_RIGHT | ROUND_CORNER_BOTTOM_LEFT | ROUND_CORNER_BOTTOM_RIGHT)"

// Constants for `button_activation_type`.
{DEFINE ACTIVATE_ONPRESSEDANDRELEASED} 0
{DEFINE ACTIVATE_ONPRESSED} 1
{DEFINE ACTIVATE_ONRELEASED} 2

// Characters from the `9ui_icons` font.
{DEFINE ICON_BLOCK} 0
{DEFINE ICON_RIGHT} >
{DEFINE ICON_BASKET} B
{DEFINE ICON_CHAT} C
{DEFINE ICON_GLOBE} E  // Earth
{DEFINE ICON_FILM} F
{DEFINE ICON_GEAR} G
{DEFINE ICON_MEDAL} M
{DEFINE ICON_PLAY} P
{DEFINE ICON_QUIT} Q
{DEFINE ICON_SUITCASE} S
{DEFINE ICON_TERMINAL} T
{DEFINE ICON_WRENCH} W
{DEFINE ICON_CONTRACKER} c
{DEFINE ICON_GEARS} g

// Z-order.
{DEFINE zPos.DashboardDimmer} 1000  // hardcoded
{DEFINE zPos.Background} 1100
{DEFINE zPos.MMDashboard} 1200
{DEFINE zPos.SideBar} 1300
{DEFINE zPos.MMSidePanel} 1400
